"""Question difficulty: the empty state, the estimator, and whether it predicts.

Three kinds of test here, and the third is the one that matters.

The first kind holds the *absence* in place. All 6,886 questions used to carry a
literal difficulty of 3, and the failure mode this module is defending against
is somebody helpfully filling the column back in — so there is a test that reads
the application source and fails if anything assigns to `published_difficulty`.

The second kind checks the arithmetic: that a correct answer makes an item look
easier and its answerer look stronger, that the step shrinks as evidence
accumulates, and that the provenance ladder cannot be climbed without evidence.

The third runs the estimator over a synthetic corpus generated by a *different*
model and asserts that the ratings predict held-out responses better than a
model that knows the student and nothing about the question. A difficulty
estimate that fails that is not a difficulty estimate, and this project has a
long enough history of instruments agreeing with whatever they are pointed at
that the check belongs in the suite rather than in a report nobody re-runs.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from app import calibration
from app.extensions import db
from app.models import Attempt, LearnerRating, Question, QuestionCalibration, SessionItem, User

from test_progress import (  # noqa: F401
    add_question,
    app,
    create_game,
    explanation,
    login,
    run_session,
    stub_coaching,
)


APP_DIR = Path(__file__).resolve().parents[1] / "app"


def student(handle: str) -> str:
    """A real account, because `learner_ratings.user_id` is a real foreign key.

    A rating that could be filed against a user id nobody owns is a rating that
    outlives the account it describes, which is both a data-protection problem
    and a way for an ability estimate to be silently attributed to the wrong
    person.
    """
    existing = User.query.filter_by(email=f"{handle}@example.test").first()
    if existing:
        return existing.id
    user = User(email=f"{handle}@example.test", display_name=handle)
    db.session.add(user)
    db.session.flush()
    return user.id


# ---------------------------------------------------------------------------
# The empty state, which is the whole point
# ---------------------------------------------------------------------------


def test_the_ingest_path_never_states_a_difficulty():
    """`seed.py` used to write `question.difficulty = 3` on every row.

    The upstream datasets carry no difficulty column at any revision, so there
    is nothing to write, and writing one anyway is what put a constant in front
    of a language model for the entire life of the application.
    """
    source = (APP_DIR / "seed.py").read_text(encoding="utf-8")
    assert "difficulty = 3" not in source
    assert "question.published_difficulty" not in source


def test_nothing_in_the_application_writes_a_published_difficulty():
    """`published_difficulty` means "the test maker stated one" and nothing else.

    An estimate written here would be indistinguishable from a real rating
    afterwards, which is precisely the property that made the old column
    worthless. The estimate has its own table and its own provenance.
    """
    offenders = []
    for path in sorted(APP_DIR.glob("*.py")):
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            if "published_difficulty" not in stripped or "=" not in stripped:
                continue
            # The column declaration itself is the one legitimate assignment.
            if "db.Column" in stripped:
                continue
            # A keyword argument or a comparison is fine; an assignment is not.
            head = stripped.split("=", 1)[0]
            if head.rstrip().endswith("published_difficulty"):
                offenders.append(f"{path.name}:{number}: {stripped}")
    assert not offenders, (
        "something assigns a published difficulty. Only an importer of a real "
        f"published rating may do that, and there is not one: {offenders}"
    )


def test_a_seeded_question_has_no_difficulty_and_no_calibration_row(app):  # noqa: F811
    with app.app_context():
        question = Question.query.first()
        assert question.published_difficulty is None
        assert question.calibration is None
        reading = calibration.signal(question)
        assert reading["status"] == "uncalibrated"
        assert reading["rating"] is None
        assert reading["band"] is None
        assert reading["usable_for_targeting"] is False


def test_the_bank_summary_reports_the_bank_as_uncalibrated(app):  # noqa: F811
    with app.app_context():
        summary = calibration.bank_summary()
        assert summary["questions"] == 30
        assert summary["published"] == 0
        assert summary["uncalibrated"] == 30
        assert summary["calibrated"] == 0


# ---------------------------------------------------------------------------
# The arithmetic
# ---------------------------------------------------------------------------


def test_the_response_model_reduces_to_plain_elo_without_a_guessing_floor():
    assert calibration.expected_correct(0.0, 0.0, 0.0) == pytest.approx(0.5)
    assert calibration.expected_correct(1.0, 0.0, 0.0) == pytest.approx(calibration.logistic(1.0))
    # With a floor, a hopeless student still has the floor.
    assert calibration.expected_correct(-8.0, 0.0, 0.2) == pytest.approx(0.2, abs=1e-3)
    assert calibration.expected_correct(0.0, 0.0, 0.2) == pytest.approx(0.6)


def test_a_correct_answer_makes_the_item_easier_and_the_student_stronger():
    match = calibration.Match(theta=0.0, difficulty=0.0, is_correct=True, guess=0.2)
    assert match.next_difficulty(0.0) < 0.0
    assert match.next_theta(0.0) > 0.0
    missed = calibration.Match(theta=0.0, difficulty=0.0, is_correct=False, guess=0.2)
    assert missed.next_difficulty(0.0) > 0.0
    assert missed.next_theta(0.0) < 0.0


def test_a_correct_answer_on_a_hopeless_item_barely_moves_anything():
    """Most of a right answer on an impossible item is the guess, not knowledge.

    Plain Elo cannot express that: it reads the same outcome as an enormous
    upset and runs the rating away. The q/p factor is what stops it.
    """
    hopeless = calibration.Match(theta=-3.0, difficulty=3.0, is_correct=True, guess=0.2)
    plausible = calibration.Match(theta=0.0, difficulty=0.0, is_correct=True, guess=0.2)
    # Same accumulated information on both, so only the response differs.
    hopeless_move = abs(hopeless.next_difficulty(1.0) - 3.0)
    plausible_move = abs(plausible.next_difficulty(1.0) - 0.0)
    assert hopeless_move < plausible_move / 4
    # The surprise is larger on the hopeless item and the move is smaller, which
    # is the whole difference between this and plain Elo.
    assert hopeless.surprise > plausible.surprise


def test_the_step_shrinks_as_evidence_accumulates():
    first = calibration.item_step_size(0.0)
    later = calibration.item_step_size(10.0)
    much_later = calibration.item_step_size(100.0)
    assert first > later > much_later
    assert much_later < 0.02
    # A student's step is floored, because ability keeps moving and a rating
    # that stops moving stops tracking it.
    assert calibration.learner_step_size(1e6) == pytest.approx(
        1.0 / (calibration.LEARNER_PRIOR_PRECISION + calibration.LEARNER_INFORMATION_CAP)
    )


def test_an_uninformative_response_carries_almost_no_information():
    """Somebody who was always going to get it right says nothing about the item."""
    matched = calibration.response_information(0.0, 0.0, 0.2)
    mismatched = calibration.response_information(4.0, -4.0, 0.2)
    assert matched > mismatched * 50


def test_ratings_cannot_run_away():
    difficulty = 0.0
    for _ in range(500):
        match = calibration.Match(theta=3.0, difficulty=difficulty, is_correct=True, guess=0.2)
        difficulty = match.next_difficulty(0.0)  # never let the step decay
    assert -calibration.RATING_LIMIT <= difficulty <= calibration.RATING_LIMIT


# ---------------------------------------------------------------------------
# Provenance
# ---------------------------------------------------------------------------


def test_the_status_ladder_cannot_be_climbed_without_evidence():
    assert calibration.status_for(0, 0.0) == "uncalibrated"
    assert calibration.status_for(4, 1.0) == "provisional"
    assert calibration.status_for(11, 3.0) == "provisional"
    assert calibration.status_for(12, 3.0) == "estimated"
    # Fifty responses, but all of them uninformative: still not calibrated.
    assert calibration.status_for(60, 2.0) == "estimated"
    assert calibration.status_for(60, 20.0) == "calibrated"


def test_a_band_is_withheld_until_the_rating_is_worth_reading(app):  # noqa: F811
    with app.app_context():
        question = Question.query.first()
        row = QuestionCalibration(
            question_id=question.id,
            rating=1.5,
            information=1.0,
            responses=3,
            status="provisional",
        )
        db.session.add(row)
        db.session.flush()
        reading = calibration.signal(question, row, centre=0.0)
        assert reading["status"] == "provisional"
        assert reading["rating"] == 1.5
        assert reading["band"] is None
        assert reading["usable_for_targeting"] is False

        row.responses = 60
        row.information = 20.0
        row.status = calibration.status_for(row.responses, row.information)
        reading = calibration.signal(question, row, centre=0.0)
        assert reading["status"] == "calibrated"
        assert reading["band"] == 5
        assert reading["usable_for_targeting"] is True


def test_a_simulated_response_permanently_marks_the_row(app):  # noqa: F811
    """A demo seeder must not be able to hand an item a rating that looks earned.

    This project shipped a demo seeder that bypassed the real selector once
    already. `origin` is the column that makes the next one visible.
    """
    with app.app_context():
        question = Question.query.first()
        calibration.record_response(student("sim-1"), question, True, origin=calibration.ORIGIN_SIMULATED)
        db.session.flush()
        row = question.calibration
        assert row.origin == "simulated"

        # A real response afterwards cannot launder it back.
        calibration.record_response(student("sim-2"), question, False)
        db.session.flush()
        assert row.origin == "simulated"
        assert calibration.signal(question, row)["usable_for_targeting"] is False


def test_a_marked_block_taints_every_response_recorded_inside_it(app):  # noqa: F811
    """The seeders answer through `submit_attempt` and cannot pass an origin.

    So the origin has to reach `record_response` some other way, and the marker
    is it. Outside the block the default is unchanged, which is what stops a
    process that ran a seeder once from marking the rest of its life synthetic.
    """
    with app.app_context():
        inside, outside = Question.query.limit(2).all()
        with calibration.responses_marked(calibration.ORIGIN_SIMULATED):
            calibration.record_response(student("ambient-1"), inside, True)
        calibration.record_response(student("ambient-2"), outside, True)
        db.session.flush()
        assert inside.calibration.origin == "simulated"
        assert outside.calibration.origin == "responses"


def test_an_unknown_origin_is_refused(app):  # noqa: F811
    with app.app_context():
        with pytest.raises(ValueError):
            calibration.responses_marked("plausible").__enter__()
        with pytest.raises(ValueError):
            calibration.record_response(student("bad-origin"), Question.query.first(), True, origin="vibes")


def test_the_marker_is_restored_even_when_the_run_fails(app):  # noqa: F811
    with app.app_context():
        with pytest.raises(RuntimeError):
            with calibration.responses_marked(calibration.ORIGIN_SIMULATED):
                raise RuntimeError("seeding blew up halfway through")
        calibration.record_response(student("after-failure"), Question.query.first(), True)
        db.session.flush()
        assert Question.query.first().calibration.origin == "responses"


def test_every_seeder_declares_its_answers_synthetic():
    """A demo account's forty thousand invented answers are not evidence.

    Both seeders write attempts — one by hand, one through `submit_attempt` —
    and both therefore move the difficulty ratings. Neither may do so under an
    origin that a consumer is allowed to steer on.
    """
    scripts = Path(__file__).resolve().parents[1] / "scripts"
    for name in ("seed_demo.py", "seed_demo_learner.py"):
        source = (scripts / name).read_text(encoding="utf-8")
        assert "responses_marked(calibration.ORIGIN_SIMULATED)" in source, (
            f"{name} writes attempts without declaring them synthetic"
        )
        # Re-running a seeder must not stack a second history on the first.
        assert "delete(QuestionCalibration)" in source, f"{name} does not clear the ratings it wrote"


def test_recording_a_response_writes_both_sides_of_the_match(app):  # noqa: F811
    with app.app_context():
        question = Question.query.filter_by(section="Logical Reasoning").first()
        user_id = student("match-1")
        calibration.record_response(user_id, question, True)
        db.session.flush()
        item = question.calibration
        learner = LearnerRating.query.filter_by(user_id=user_id, scope="Logical Reasoning").one()
        assert item.responses == 1 and item.correct == 1
        assert item.rating < 0  # a right answer says the item is easier
        assert learner.rating > 0
        assert learner.responses == 1
        assert item.blind_responses == 1
        assert item.targeted_responses == 0
        assert item.status == "provisional"


def test_targeted_exposure_is_kept_out_of_the_blind_rating(app):  # noqa: F811
    with app.app_context():
        question = Question.query.filter_by(section="Logical Reasoning").first()
        for index in range(6):
            calibration.record_response(
                student(f"blind-{index}"), question, True, exposure=calibration.EXPOSURE_BLIND
            )
        blind_after = question.calibration.blind_rating
        for index in range(6):
            calibration.record_response(
                student(f"targeted-{index}"), question, False, exposure=calibration.EXPOSURE_TARGETED
            )
        db.session.flush()
        row = question.calibration
        assert row.responses == 12
        assert row.blind_responses == 6
        assert row.targeted_responses == 6
        # The blind rating saw none of the six targeted responses.
        assert row.blind_rating == pytest.approx(blind_after)
        # …and the naive rating did, so the two have separated. That gap is the
        # measurement of the distortion.
        reading = calibration.signal(question, row, centre=0.0)
        assert reading["selection_bias_gap"] is not None
        assert abs(reading["selection_bias_gap"]) > 0.05


def test_an_unknown_exposure_policy_is_refused(app):  # noqa: F811
    with app.app_context():
        question = Question.query.first()
        with pytest.raises(ValueError):
            calibration.record_response(student("bad-exposure"), question, True, exposure="whatever")


# ---------------------------------------------------------------------------
# The randomisation that keeps the estimate identifiable
# ---------------------------------------------------------------------------


def test_the_exposure_draw_is_stable_and_reserves_a_quarter_of_slots():
    first = calibration.exposure_draw("u1", "s1", 3)
    assert calibration.exposure_draw("u1", "s1", 3) == first
    assert first["policy"] in {"random", "targeted"}

    draws = [calibration.exposure_draw("u1", f"s{index}", index % 8) for index in range(4000)]
    random_share = sum(draw["policy"] == "random" for draw in draws) / len(draws)
    assert calibration.RANDOM_HOLDOUT_SHARE - 0.03 < random_share < calibration.RANDOM_HOLDOUT_SHARE + 0.03
    # The propensity on the row is the probability of the arm that happened, so
    # a later inverse-propensity fit does not have to reconstruct the scheme.
    for draw in draws[:50]:
        expected = (
            calibration.RANDOM_HOLDOUT_SHARE
            if draw["policy"] == "random"
            else 1 - calibration.RANDOM_HOLDOUT_SHARE
        )
        assert draw["propensity"] == pytest.approx(expected)


def test_selection_still_ignores_difficulty_entirely():
    """The scope boundary, asserted rather than remembered.

    This agent's job was to produce the signal, not to consume it: session
    construction belongs to another workstream and has been left a seam. If
    selection starts reading a rating, it must also start calling
    `exposure_draw` and writing `SessionItem.exposure_policy`, or the estimate
    silently loses the randomisation that identifies it. This test failing is
    the reminder to do the second half.
    """
    services = (APP_DIR / "services.py").read_text(encoding="utf-8")
    selection = services[services.index("def select_random_questions") : services.index("def select_diagnostic_questions")]
    assert "calibration" not in selection
    assert "difficulty" not in selection
    assert "exposure_policy" not in selection


# ---------------------------------------------------------------------------
# The live path
# ---------------------------------------------------------------------------


def test_answering_a_question_rates_it(app):  # noqa: F811
    client = app.test_client()
    headers = login(client, "calibrate@example.test")
    create_game(client, headers)
    run_session(app, client, headers, "calibrate", size=4, correct=3)

    with app.app_context():
        rated = QuestionCalibration.query.all()
        assert len(rated) == 4, "every answered question should have picked up a rating"
        assert all(row.responses == 1 for row in rated)
        assert all(row.origin == "responses" for row in rated)
        assert all(row.status == "provisional" for row in rated)
        # Three right and one wrong, so three items moved down and one up.
        assert sum(row.rating < 0 for row in rated) == 3
        assert sum(row.rating > 0 for row in rated) == 1

        # Exposure travelled from the served item onto the attempt.
        assert {item.exposure_policy for item in SessionItem.query.all()} == {"blind"}
        assert {attempt.exposure_policy for attempt in Attempt.query.all()} == {"blind"}
        assert all(row.blind_responses == 1 for row in rated)

        # One ability rating per section the run touched, never one per student:
        # weakness at Reading Comprehension must not make Logical Reasoning items
        # look easy.
        learners = LearnerRating.query.all()
        assert {row.scope for row in learners} <= {"Logical Reasoning", "Reading Comprehension"}
        assert len({row.user_id for row in learners}) == 1
        assert sum(row.responses for row in learners) == 4


def test_resubmitting_the_same_answer_does_not_count_twice(app):  # noqa: F811
    client = app.test_client()
    headers = login(client, "idempotent@example.test")
    create_game(client, headers)
    session = client.post("/v1/study-sessions", json={"size": 4}, headers=headers).json["session"]
    item = client.get(f"/v1/study-sessions/{session['id']}", headers=headers).json["session"]["current_item"]
    payload = {
        "item_id": item["id"],
        "selected_label": "C",
        "strategy_applied": True,
        "confidence": 3,
        "reasoning": explanation("idempotent"),
    }
    for _ in range(3):
        response = client.post(
            f"/v1/study-sessions/{session['id']}/attempts",
            json=payload,
            headers={**headers, "Idempotency-Key": "idempotent-1"},
        )
        assert response.status_code == 200

    with app.app_context():
        rows = QuestionCalibration.query.all()
        assert len(rows) == 1
        assert rows[0].responses == 1


def test_the_history_payload_reports_what_is_known_rather_than_a_constant(app):  # noqa: F811
    client = app.test_client()
    headers = login(client, "history-difficulty@example.test")
    create_game(client, headers)
    run_session(app, client, headers, "history-difficulty", size=4, correct=2)

    page = client.get("/v1/history/attempts?detail=true&limit=4", headers=headers)
    assert page.status_code == 200
    for row in page.json["attempts"]:
        question = row["question"]
        assert question["published_difficulty"] is None
        difficulty = question["difficulty"]
        assert difficulty["status"] == "provisional"
        assert difficulty["responses"] == 1
        assert difficulty["band"] is None
        assert difficulty["usable_for_targeting"] is False


def test_the_coaching_prompt_no_longer_asserts_a_difficulty(app):  # noqa: F811
    from app.coaching import _question_data

    with app.app_context():
        question = Question.query.first()
        data = _question_data(question)
        assert data["published_difficulty"] is None
        assert data["measured_difficulty"]["status"] == "uncalibrated"
        assert "difficulty" not in {key for key in data if key == "difficulty"}

        for index in range(20):
            calibration.record_response(student(f"coach-{index}"), question, index % 3 == 0)
        db.session.flush()
        db.session.expire(question)
        measured = _question_data(question)["measured_difficulty"]
        assert measured["status"] == "estimated"
        assert measured["band_1_easiest_to_5_hardest"] in {1, 2, 3, 4, 5}
        assert measured["responses"] == 20
        assert "not published by the test maker" in measured["note"]


def test_the_coaching_prompt_refuses_a_difficulty_built_from_invented_answers(app):  # noqa: F811
    """Twenty seeded answers are twenty facts about a seeder, not about an item."""
    from app.coaching import _question_data

    with app.app_context():
        question = Question.query.offset(1).first()
        with calibration.responses_marked(calibration.ORIGIN_SIMULATED):
            for index in range(20):
                calibration.record_response(student(f"fake-coach-{index}"), question, index % 3 == 0)
        db.session.flush()
        db.session.expire(question)
        measured = _question_data(question)["measured_difficulty"]
        assert measured["status"] == "uncalibrated"
        assert "band_1_easiest_to_5_hardest" not in measured


# ---------------------------------------------------------------------------
# Does it predict? The check that decides whether any of the above matters
# ---------------------------------------------------------------------------


def test_the_rating_predicts_held_out_responses_better_than_knowing_only_the_student():
    """The claim this whole module rests on, run as a test rather than a report.

    The corpus is generated by a 2PL model with per-item guessing floors and
    ability that drifts upward — three ways of being different from what the
    estimator assumes. The `learner` baseline is given the student's identity
    and nothing about the question, so everything the item rating is worth
    appears as the gap between it and `elo`.

    The thresholds are set well below the measured values (log loss 0.609
    against 0.642, AUC 0.694) so that ordinary drift does not fail the suite,
    but a rating that has stopped carrying signal will.
    """
    from scripts.calibration_lab import evaluate, simulate

    simulation = simulate(items=250, learners=100, responses_per_learner=60, seed=4242)
    result = evaluate(simulation.responses, holdout=0.3, seed=99)
    scores = {row["model"]: row for row in result["models"]}

    assert scores["elo"]["log_loss"] < scores["learner"]["log_loss"]
    assert scores["elo"]["log_loss"] < scores["global"]["log_loss"]
    assert result["elo_vs_learner_log_loss"] > 0.015
    assert scores["elo"]["auc"] > 0.65
    # The ratings order the items the way the held-out responses do.
    assert result["rating_vs_holdout_difficulty_spearman"] > 0.4


def test_the_information_scaled_step_beats_every_constant_it_replaced():
    """Complexity has to pay for itself, so the step rule is measured too.

    `K = 1/(prior + ΣI)` is two functions and an accumulator more than plain
    Elo's constant. It is worth having only if it predicts better than the best
    constant anyone would have picked, run over the same responses in the same
    order.
    """
    from scripts.calibration_lab import evaluate, simulate

    simulation = simulate(items=250, learners=100, responses_per_learner=60, seed=4242)
    result = evaluate(
        simulation.responses, holdout=0.3, seed=99, fixed_k_arms=(0.1, 0.2, 0.4, 0.8)
    )
    scores = {row["model"]: row for row in result["models"]}
    constants = [row for name, row in scores.items() if name.startswith("elo_fixed_k_")]
    assert len(constants) == 4
    assert scores["elo"]["log_loss"] < min(row["log_loss"] for row in constants)
    assert scores["elo"]["auc"] > max(row["auc"] for row in constants)


def test_the_rating_recovers_the_difficulties_that_generated_the_data():
    from scripts.calibration_lab import recovery, replay, simulate

    simulation = simulate(items=250, learners=100, responses_per_learner=100, seed=4242)
    recovered = recovery(replay(simulation.responses), simulation.truth)
    assert recovered["mean_responses_per_item"] > 30
    # A Rasch estimator cannot recover a 2PL difficulty exactly, so this is a
    # rank claim rather than an identity one.
    assert recovered["spearman"] > 0.8
    assert abs(recovered["bias"]) < 0.1


def test_holding_the_random_slice_out_reproduces_the_rating_from_unbiased_exposure_alone():
    """What `blind_rating` buys, measured.

    Under a selector that always targets, there is no unbiased slice at all and
    nothing to check the naive rating against. Reserving a quarter of slots
    produces a second estimate built only from exposure that could not depend on
    difficulty — noisier, because it has a quarter of the data, and that is the
    price of being able to check at all.
    """
    from scripts.calibration_lab import recovery, replay, simulate

    without = simulate(items=200, learners=100, responses_per_learner=80, seed=77, targeting=1.0)
    assert recovery(replay(without.responses, unbiased_only=True), without.truth)["items"] == 0

    with_slice = simulate(
        items=200, learners=100, responses_per_learner=80, seed=77, targeting=1.0, random_holdout=0.25
    )
    checkable = recovery(replay(with_slice.responses, unbiased_only=True), with_slice.truth)
    assert checkable["items"] > 150
    assert checkable["spearman"] > 0.5
