export type SceneCategory = 'casework' | 'learning' | 'firm' | 'world' | 'social' | 'internal'
export type SceneLayout =
  | 'office' | 'reception' | 'conference' | 'workspace' | 'resolution' | 'shop'
  | 'library' | 'lab' | 'deal' | 'court' | 'academy' | 'bullpen' | 'interview'
  | 'operations' | 'hall' | 'gallery' | 'records' | 'boardroom' | 'partner'
  | 'field' | 'courthouse' | 'cafe' | 'directory' | 'rooftop' | 'executive' | 'review'

export type SceneAction = { label: string; detail: string; to: string }
export type SceneDefinition = {
  id: string
  slug: string
  title: string
  shortTitle: string
  kicker: string
  purpose: string
  category: SceneCategory
  layout: SceneLayout
  minTier: number
  internal?: boolean
  district: string
  position: { x: number; y: number }
  palette: { wall: string; floor: string; accent: string; dark: string }
  props: string[]
  cast: string[]
  actions: SceneAction[]
}

const route = {
  office: '/office', docket: '/cases', active: '/cases?view=active', intake: '/cases?view=intake', review: '/cases?view=review', firm: '/firm', map: '/map',
  staff: '/firm?tab=staff', achievements: '/firm?tab=achievements',
}

const amber = { wall: '#9b754e', floor: '#584034', accent: '#efc55d', dark: '#17283a' }
const teal = { wall: '#547873', floor: '#354e4e', accent: '#6fd0c2', dark: '#132b37' }
const navy = { wall: '#405c6b', floor: '#253844', accent: '#efc55d', dark: '#101c2b' }
const plum = { wall: '#64546f', floor: '#3e3349', accent: '#d9b15e', dark: '#211a2d' }
const stone = { wall: '#91897b', floor: '#57534e', accent: '#e5bd65', dark: '#26343b' }
const blue = { wall: '#517a91', floor: '#304b5b', accent: '#f0c762', dark: '#132938' }

export const scenes: SceneDefinition[] = [
  { id: 'S01', slug: 'starter-office', title: 'Starter Office', shortTitle: 'Starter Office', kicker: 'HOME BASE', purpose: 'Start at your desk, take the next case, and watch the office grow with the practice.', category: 'firm', layout: 'office', minTier: 0, district: 'Founders Row', position: { x: 14, y: 78 }, palette: amber, props: ['Folding desk', 'Case inbox', 'Coat rack', 'Mentor station'], cast: ['YOU', 'MENTOR'], actions: [{ label: 'Return to your desk', detail: 'Go back to headquarters.', to: route.office }, { label: 'Open the Docket', detail: 'Choose rewarded work, Client Intake, or Rapid Review.', to: route.docket }, { label: 'Walk the city', detail: 'Open the City Directory.', to: route.map }] },
  { id: 'S02', slug: 'reception-docket', title: 'Reception & Docket', shortTitle: 'Docket', kicker: 'CHOOSE YOUR WORK', purpose: 'Choose rewarded casework, a client for future cases, or Rapid Review with no rewards.', category: 'casework', layout: 'reception', minTier: 0, district: 'Founders Row', position: { x: 21, y: 70 }, palette: navy, props: ['Reception desk', 'Docket board', 'Mail cubbies', 'Waiting bench'], cast: ['MAYA', 'CLIENT', 'YOU'], actions: [{ label: 'Open the Docket', detail: 'Choose or resume rewarded casework.', to: route.docket }, { label: 'Open Client Intake', detail: 'Select the contract for future cases.', to: route.intake }, { label: 'Open Rapid Review', detail: 'Revisit solved questions with no game rewards.', to: route.review }] },
  { id: 'S03', slug: 'client-intake', title: 'Client Intake', shortTitle: 'Client Intake', kicker: 'FUTURE CONTRACTS', purpose: 'Choose client and fee terms for future cases without changing the matter already open.', category: 'casework', layout: 'conference', minTier: 0, district: 'Founders Row', position: { x: 28, y: 78 }, palette: teal, props: ['Round table', 'Client folder', 'Privacy glass', 'Water carafe'], cast: ['CLIENT', 'YOU', 'MAYA'], actions: [{ label: 'Choose a client contract', detail: 'Set the client for future cases.', to: route.intake }, { label: 'Resume active work', detail: 'Return to the open file when one is waiting.', to: route.active }, { label: 'Back to the Docket', detail: 'Choose the next kind of work.', to: route.docket }] },
  { id: 'S04', slug: 'case-workspace', title: 'Case Workspace', shortTitle: 'Case Workspace', kicker: 'ACTIVE MATTER', purpose: 'Read the record, choose an answer, and explain the reasoning.', category: 'casework', layout: 'workspace', minTier: 0, district: 'Founders Row', position: { x: 37, y: 69 }, palette: navy, props: ['Argument board', 'Reading lamp', 'Evidence thread', 'Case timer'], cast: ['YOU', 'MENTOR'], actions: [{ label: 'Resume active work', detail: 'Return to the open file with its original client terms.', to: route.active }, { label: 'Meet with your coach', detail: 'Visit Mentor Conference.', to: '/world/mentor-conference' }, { label: 'Investigate the argument', detail: 'Open the Investigation Lab.', to: '/world/investigation-lab' }] },
  { id: 'S05', slug: 'mentor-conference', title: 'Mentor Conference', shortTitle: 'Mentor', kicker: 'FIRST-ERROR REVIEW', purpose: 'Work with your coach to find the first weak step and rebuild the argument.', category: 'learning', layout: 'conference', minTier: 0, district: 'Founders Row', position: { x: 43, y: 58 }, palette: plum, props: ['Redline sheet', 'Logic cards', 'Quiet lamp', 'Appeal clock'], cast: ['MENTOR', 'YOU'], actions: [{ label: 'Resume active work', detail: 'Return to the open file and apply the revised method.', to: route.active }, { label: 'Open Rapid Review', detail: 'Revisit solved questions with no game rewards.', to: route.review }, { label: 'Research a method', detail: 'Open the library.', to: '/world/research-library' }] },
  { id: 'S06', slug: 'case-resolution', title: 'Case Resolution', shortTitle: 'Resolution', kicker: 'VERDICT & SETTLEMENT', purpose: 'Review the answer, your reasoning, and the fee before closing the matter.', category: 'casework', layout: 'resolution', minTier: 0, district: 'Founders Row', position: { x: 49, y: 73 }, palette: teal, props: ['Verdict seal', 'Settlement ledger', 'Client letter', 'Redline stack'], cast: ['YOU', 'MENTOR', 'CLIENT'], actions: [{ label: 'Return to the Docket', detail: 'Choose the next kind of work.', to: route.docket }, { label: 'File the result', detail: 'Visit the Portfolio Gallery.', to: '/world/portfolio-gallery' }, { label: 'Invest the fee', detail: 'Open the Design Studio.', to: '/world/firm-shop' }] },
  { id: 'S07', slug: 'firm-shop', title: 'Design Studio', shortTitle: 'Design Studio', kicker: 'VISIBLE PROGRESS', purpose: 'Invest earned fees in upgrades that improve the practice and change the office.', category: 'firm', layout: 'shop', minTier: 0, district: 'Founders Row', position: { x: 58, y: 79 }, palette: amber, props: ['Material swatches', 'Furniture plans', 'Upgrade plinths', 'Tailor mirror'], cast: ['NINA', 'YOU'], actions: [{ label: 'Open the catalog', detail: 'Purchase available upgrades.', to: route.firm }, { label: 'Plan staff stations', detail: 'Review staff investments.', to: route.staff }, { label: 'Preview headquarters', detail: 'Return to the office.', to: route.office }] },
  { id: 'S08', slug: 'research-library', title: 'Research Library', shortTitle: 'Library', kicker: 'DOCTRINE & METHODS', purpose: 'Review methods, study explanations, and retrieve the ideas you need.', category: 'learning', layout: 'library', minTier: 1, district: 'Learning Quarter', position: { x: 18, y: 37 }, palette: amber, props: ['Book walls', 'Rolling ladder', 'Reading table', 'Reference terminal'], cast: ['AVERY', 'YOU'], actions: [{ label: 'Apply the method', detail: 'Resume the active file and test the method.', to: route.active }, { label: 'Visit Skills Academy', detail: 'Review your skill progress.', to: '/world/skills-academy' }, { label: 'Trace prior reasoning', detail: 'Open the Records Room.', to: '/world/records-room' }] },
  { id: 'S09', slug: 'investigation-lab', title: 'Investigation Lab', shortTitle: 'Investigation Lab', kicker: 'ARGUMENT FORENSICS', purpose: 'Break Logical Reasoning into evidence, conclusion, gap, and trap.', category: 'learning', layout: 'lab', minTier: 1, district: 'Learning Quarter', position: { x: 28, y: 48 }, palette: navy, props: ['Evidence wall', 'Argument thread', 'Magnifier', 'Trap drawers'], cast: ['THEO', 'YOU'], actions: [{ label: 'Resume active work', detail: 'Return to the open Logical Reasoning file.', to: route.active }, { label: 'Return to the workspace', detail: 'Open the Case Workspace.', to: '/world/case-workspace' }, { label: 'Open Rapid Review', detail: 'Revisit solved arguments with no game rewards.', to: route.review }] },
  { id: 'S10', slug: 'due-diligence', title: 'Due Diligence Room', shortTitle: 'Due Diligence', kicker: 'PASSAGE ANALYSIS', purpose: 'Map each passage’s viewpoints, structure, roles, and inferences.', category: 'learning', layout: 'deal', minTier: 1, district: 'Learning Quarter', position: { x: 39, y: 38 }, palette: blue, props: ['Passage wall', 'Viewpoint cards', 'Risk matrix', 'Deal table'], cast: ['AVERY', 'PARTNER', 'YOU'], actions: [{ label: 'Resume active work', detail: 'Return to the open Reading Comprehension file.', to: route.active }, { label: 'Review investments', detail: 'Visit the Capital Boardroom.', to: '/world/capital-boardroom' }, { label: 'Check the passage map', detail: 'Visit the library.', to: '/world/research-library' }] },
  { id: 'S11', slug: 'appeals-chamber', title: 'Appeals Chamber', shortTitle: 'Appeals', kicker: 'RAPID REVIEW', purpose: 'Return to solved questions for retrieval practice. No game rewards are earned here.', category: 'learning', layout: 'court', minTier: 1, district: 'Civic Center', position: { x: 50, y: 29 }, palette: plum, props: ['Appeals bench', 'Redline docket', 'Review clock', 'Precedent shelf'], cast: ['REVIEWER', 'MENTOR', 'YOU'], actions: [{ label: 'Open Rapid Review', detail: 'Revisit solved questions with no game rewards.', to: route.review }, { label: 'Review the redline', detail: 'Return to Mentor Conference.', to: '/world/mentor-conference' }, { label: 'File recovered work', detail: 'Open the Portfolio.', to: '/world/portfolio-gallery' }] },
  { id: 'S12', slug: 'skills-academy', title: 'Skills Academy', shortTitle: 'Skills Academy', kicker: 'GUIDED → INDEPENDENT', purpose: 'Track each skill as you move from guided practice to independent work.', category: 'learning', layout: 'academy', minTier: 1, district: 'Learning Quarter', position: { x: 59, y: 38 }, palette: teal, props: ['Skill map', 'Training dais', 'Practice stations', 'Mastery banners'], cast: ['MENTOR', 'AVERY', 'YOU'], actions: [{ label: 'Open the Docket', detail: 'Choose the next rewarded file.', to: route.docket }, { label: 'Enter Mock Court', detail: 'Practice under time pressure.', to: '/world/mock-courtroom' }, { label: 'Review the method', detail: 'Return to the library.', to: '/world/research-library' }] },
  { id: 'S13', slug: 'staff-bullpen', title: 'Staff Bullpen', shortTitle: 'Staff Bullpen', kicker: 'YOUR TEAM', purpose: 'See your team, its capacity, and how each role supports the practice.', category: 'firm', layout: 'bullpen', minTier: 2, district: 'Firm Campus', position: { x: 65, y: 70 }, palette: navy, props: ['Shared desks', 'Assignment board', 'Printer bank', 'Team lockers'], cast: ['MAYA', 'ASSOCIATE', 'NINA', 'YOU'], actions: [{ label: 'Manage the team', detail: 'Review available staff.', to: route.staff }, { label: 'Open interviews', detail: 'Visit the Hiring Room.', to: '/world/hiring-room' }, { label: 'Review assignments', detail: 'Visit Operations.', to: '/world/operations-office' }] },
  { id: 'S14', slug: 'hiring-room', title: 'Hiring Room', shortTitle: 'Hiring Room', kicker: 'BUILD THE BENCH', purpose: 'Compare candidates and hire the right support for the firm.', category: 'firm', layout: 'interview', minTier: 2, district: 'Firm Campus', position: { x: 73, y: 77 }, palette: amber, props: ['Interview table', 'Candidate files', 'Role board', 'Glass door'], cast: ['NINA', 'CANDIDATE', 'YOU'], actions: [{ label: 'Review candidates', detail: 'Open the staff catalog.', to: route.staff }, { label: 'Tour the bullpen', detail: 'See the current team.', to: '/world/staff-bullpen' }, { label: 'Check the budget', detail: 'Open firm management.', to: route.firm }] },
  { id: 'S15', slug: 'operations-office', title: 'Operations Office', shortTitle: 'Operations', kicker: 'WEEKLY CAPACITY', purpose: 'Review active work, upcoming reviews, and a sustainable weekly pace.', category: 'firm', layout: 'operations', minTier: 2, district: 'Firm Campus', position: { x: 80, y: 63 }, palette: blue, props: ['Capacity board', 'Calendar wall', 'Case trays', 'Workflow screen'], cast: ['NINA', 'MAYA', 'YOU'], actions: [{ label: 'Open the Docket', detail: 'Choose or resume today’s rewarded work.', to: route.docket }, { label: 'Open Rapid Review', detail: 'Revisit solved questions with no game rewards.', to: route.review }, { label: 'Manage the firm', detail: 'Review firm investments.', to: route.firm }] },
  { id: 'S16', slug: 'practice-group-hall', title: 'Practice Group Hall', shortTitle: 'Practice Groups', kicker: 'SPECIALIZATION', purpose: 'Balance practice across the skills that need the most attention.', category: 'firm', layout: 'hall', minTier: 2, district: 'Firm Campus', position: { x: 61, y: 57 }, palette: teal, props: ['Group doors', 'Progress map', 'Weekly brief', 'Team banners'], cast: ['PARTNER', 'ASSOCIATE', 'YOU'], actions: [{ label: 'Train a weak group', detail: 'Visit Skills Academy.', to: '/world/skills-academy' }, { label: 'Manage assignments', detail: 'Open Operations.', to: '/world/operations-office' }, { label: 'Enter Mock Court', detail: 'Practice independently under time pressure.', to: '/world/mock-courtroom' }] },
  { id: 'S17', slug: 'mock-courtroom', title: 'Mock Courtroom', shortTitle: 'Mock Court', kicker: 'INDEPENDENT PRACTICE', purpose: 'Test independent reasoning under optional time pressure.', category: 'learning', layout: 'court', minTier: 2, district: 'Civic Center', position: { x: 69, y: 44 }, palette: navy, props: ['Judge bench', 'Counsel tables', 'Hearing clock', 'Observation rail'], cast: ['JUDGE', 'YOU', 'MENTOR'], actions: [{ label: 'Resume active work', detail: 'Return to the open independent file.', to: route.active }, { label: 'Train first', detail: 'Visit Skills Academy.', to: '/world/skills-academy' }, { label: 'Return to practice groups', detail: 'Open the hall.', to: '/world/practice-group-hall' }] },
  { id: 'S18', slug: 'portfolio-gallery', title: 'Portfolio Gallery', shortTitle: 'Portfolio', kicker: 'EVIDENCE OF GROWTH', purpose: 'Review resolved matters, corrected mistakes, and milestones you have earned.', category: 'learning', layout: 'gallery', minTier: 2, district: 'Firm Campus', position: { x: 53, y: 58 }, palette: plum, props: ['Case frames', 'Recovery wall', 'Milestone plinths', 'Firm timeline'], cast: ['YOU', 'MENTOR', 'CLIENT'], actions: [{ label: 'Review achievements', detail: 'Open earned milestones.', to: route.achievements }, { label: 'Review completed files', detail: 'Visit Records.', to: '/world/records-room' }, { label: 'Open Rapid Review', detail: 'Revisit solved questions with no game rewards.', to: route.review }] },
  { id: 'S19', slug: 'records-room', title: 'Records Room', shortTitle: 'Records', kicker: 'CASE HISTORY', purpose: 'Look back through prior attempts, written reasoning, and coach feedback.', category: 'learning', layout: 'records', minTier: 1, district: 'Learning Quarter', position: { x: 34, y: 56 }, palette: amber, props: ['Archive aisles', 'Rolling carts', 'Search terminal', 'Sealed boxes'], cast: ['MAYA', 'REVIEWER', 'YOU'], actions: [{ label: 'Resume active work', detail: 'Return to the open file and its saved draft.', to: route.active }, { label: 'Open Rapid Review', detail: 'Revisit solved questions with no game rewards.', to: route.review }, { label: 'Review question records', detail: 'Visit Content Review.', to: '/world/content-review-office' }] },
  { id: 'S20', slug: 'capital-boardroom', title: 'Capital Boardroom', shortTitle: 'Capital Boardroom', kicker: 'INVESTMENT COMMITTEE', purpose: 'Decide where earned fees can do the most for the firm.', category: 'firm', layout: 'boardroom', minTier: 3, district: 'Executive District', position: { x: 82, y: 42 }, palette: navy, props: ['Long table', 'Investment screen', 'Allocation ledger', 'City model'], cast: ['PARTNER', 'NINA', 'YOU'], actions: [{ label: 'Allocate capital', detail: 'Review firm investments.', to: route.firm }, { label: 'Review the city', detail: 'Open the City Directory.', to: route.map }, { label: 'Check diligence', detail: 'Visit the Due Diligence Room.', to: '/world/due-diligence' }] },
  { id: 'S21', slug: 'partner-office', title: 'Partner Office', shortTitle: 'Partner Office', kicker: 'LONG-RANGE COUNSEL', purpose: 'Review the firm’s progress and choose the next attainable milestone.', category: 'firm', layout: 'partner', minTier: 3, district: 'Executive District', position: { x: 76, y: 28 }, palette: navy, props: ['Partner desk', 'City window', 'Rank wall', 'Strategy table'], cast: ['PARTNER', 'YOU'], actions: [{ label: 'Review the expansion plan', detail: 'Open the city map.', to: route.map }, { label: 'Choose an investment', detail: 'Open firm management.', to: route.firm }, { label: 'Review the week', detail: 'Visit the Rooftop.', to: '/world/rooftop-skyline' }] },
  { id: 'S22', slug: 'client-site', title: 'Field Office', shortTitle: 'Client Site', kicker: 'FIELD MATTER', purpose: 'Handle a client matter away from headquarters with the same rules and records.', category: 'casework', layout: 'field', minTier: 2, district: 'Client Corridor', position: { x: 88, y: 56 }, palette: blue, props: ['Portable table', 'Client brand wall', 'Travel cases', 'City view'], cast: ['CLIENT', 'THEO', 'YOU'], actions: [{ label: 'Resume active work', detail: 'Return to the open field matter.', to: route.active }, { label: 'Open Client Intake', detail: 'Select the contract for future cases.', to: route.intake }, { label: 'Travel to court', detail: 'Visit Courthouse Steps.', to: '/world/courthouse-steps' }] },
  { id: 'S23', slug: 'courthouse-steps', title: 'Courthouse Steps', shortTitle: 'Courthouse', kicker: 'MILESTONE MATTER', purpose: 'Take on major matters while keeping the reasoning entirely your own.', category: 'world', layout: 'courthouse', minTier: 2, district: 'Civic Center', position: { x: 72, y: 17 }, palette: stone, props: ['Stone steps', 'Columns', 'Press rail', 'Case banner'], cast: ['CLIENT', 'MENTOR', 'YOU'], actions: [{ label: 'Resume active work', detail: 'Return to the open independent file.', to: route.active }, { label: 'Visit Mock Court', detail: 'Enter the training courtroom.', to: '/world/mock-courtroom' }, { label: 'Return to the city', detail: 'Open the map.', to: route.map }] },
  { id: 'S24', slug: 'break-room', title: 'Counsel Café', shortTitle: 'Counsel Café', kicker: 'QUIET MINUTE', purpose: 'Pause between matters and catch up with the team.', category: 'social', layout: 'cafe', minTier: 2, district: 'Firm Campus', position: { x: 61, y: 84 }, palette: teal, props: ['Coffee counter', 'Small tables', 'Notice board', 'Plants'], cast: ['MAYA', 'ASSOCIATE', 'NINA', 'YOU'], actions: [{ label: 'Return refreshed', detail: 'Go back to headquarters.', to: route.office }, { label: 'Return to the team floor', detail: 'Visit the Bullpen.', to: '/world/staff-bullpen' }, { label: 'Open the Docket', detail: 'Choose the next kind of work.', to: route.docket }] },
  { id: 'S25', slug: 'city-directory', title: 'City Directory', shortTitle: 'City Directory', kicker: 'FIND A DESTINATION', purpose: 'See every office, learning space, and city destination in one place.', category: 'world', layout: 'directory', minTier: 0, district: 'Citywide', position: { x: 46, y: 48 }, palette: blue, props: ['District map', 'Transit routes', 'Firm markers', 'Future lots'], cast: ['YOU', 'NINA'], actions: [{ label: 'Explore the city', detail: 'Open the full city map.', to: route.map }, { label: 'Return to headquarters', detail: 'Go back to the office.', to: route.office }, { label: 'Open the Docket', detail: 'Choose the next kind of work.', to: route.docket }] },
  { id: 'S26', slug: 'rooftop-skyline', title: 'Rooftop Terrace', shortTitle: 'Rooftop', kicker: 'WEEKLY REFLECTION', purpose: 'Step back to review the week and choose the next milestone.', category: 'social', layout: 'rooftop', minTier: 3, district: 'Executive District', position: { x: 59, y: 17 }, palette: navy, props: ['Skyline', 'Firm sign', 'Terrace', 'Weekly ledger'], cast: ['MENTOR', 'ASSOCIATE', 'YOU'], actions: [{ label: 'Review your record', detail: 'Visit the Portfolio.', to: '/world/portfolio-gallery' }, { label: 'Set the next milestone', detail: 'Visit the Partner Office.', to: '/world/partner-office' }, { label: 'Resume active work', detail: 'Return to the open file.', to: route.active }] },
  { id: 'S27', slug: 'managing-partner-floor', title: 'Managing Partner Floor', shortTitle: 'Managing Partner', kicker: 'FIRM HEADQUARTERS', purpose: 'Oversee the firm’s portfolio, expansion, and mentorship from one place.', category: 'firm', layout: 'executive', minTier: 5, district: 'Executive District', position: { x: 88, y: 16 }, palette: navy, props: ['Executive lobby', 'Global map', 'Portfolio wall', 'Mentorship table'], cast: ['PARTNER', 'ASSOCIATE', 'NINA', 'YOU'], actions: [{ label: 'Review the firm’s reach', detail: 'Open the full city map.', to: route.map }, { label: 'Review capital', detail: 'Visit the Boardroom.', to: '/world/capital-boardroom' }, { label: 'Open the Docket', detail: 'Choose the next kind of work.', to: route.docket }] },
  { id: 'S28', slug: 'content-review-office', title: 'Content Review Office', shortTitle: 'Content Review', kicker: 'INTERNAL REVIEW', purpose: 'Review question sources, duplicates, licenses, and publication status.', category: 'internal', layout: 'review', minTier: 0, internal: true, district: 'Operations Annex', position: { x: 8, y: 55 }, palette: plum, props: ['Review queues', 'Quarantine shelf', 'Audit terminal', 'Publication board'], cast: ['REVIEWER', 'AVERY', 'NINA'], actions: [{ label: 'Return to case records', detail: 'Visit the Records Room.', to: '/world/records-room' }, { label: 'Return to the city', detail: 'Open the map.', to: route.map }] },
]

export const sceneBySlug = new Map(scenes.map((scene) => [scene.slug, scene]))
export const learnerScenes = scenes.filter((scene) => !scene.internal)
