export type SceneCategory = 'casework' | 'learning' | 'firm' | 'world' | 'social' | 'internal'
export type SceneLayout =
  | 'office' | 'reception' | 'conference' | 'workspace' | 'resolution' | 'shop'
  | 'library' | 'lab' | 'deal' | 'court' | 'academy' | 'bullpen' | 'interview'
  | 'operations' | 'hall' | 'gallery' | 'records' | 'boardroom' | 'partner'
  | 'field' | 'courthouse' | 'cafe' | 'directory' | 'rooftop' | 'executive' | 'review'

export type SceneAction = { label: string; detail: string; to: string }
export type SceneDefinition = {
  id: string
  slug: string
  title: string
  shortTitle: string
  kicker: string
  purpose: string
  category: SceneCategory
  layout: SceneLayout
  minTier: number
  internal?: boolean
  district: string
  position: { x: number; y: number }
  palette: { wall: string; floor: string; accent: string; dark: string }
  props: string[]
  cast: string[]
  actions: SceneAction[]
}

const route = {
  office: '/office', cases: '/cases', firm: '/firm', map: '/map',
  staff: '/firm?tab=staff', clients: '/firm?tab=clients', achievements: '/firm?tab=achievements',
}

const amber = { wall: '#9b754e', floor: '#584034', accent: '#efc55d', dark: '#17283a' }
const teal = { wall: '#547873', floor: '#354e4e', accent: '#6fd0c2', dark: '#132b37' }
const navy = { wall: '#405c6b', floor: '#253844', accent: '#efc55d', dark: '#101c2b' }
const plum = { wall: '#64546f', floor: '#3e3349', accent: '#d9b15e', dark: '#211a2d' }
const stone = { wall: '#91897b', floor: '#57534e', accent: '#e5bd65', dark: '#26343b' }
const blue = { wall: '#517a91', floor: '#304b5b', accent: '#f0c762', dark: '#132938' }

export const scenes: SceneDefinition[] = [
  { id: 'S01', slug: 'starter-office', title: 'Shared Office / Starter Desk', shortTitle: 'Starter Office', kicker: 'HOME BASE', purpose: 'See the next useful action and the firm visibly respond to earned growth.', category: 'firm', layout: 'office', minTier: 0, district: 'Founders Row', position: { x: 14, y: 78 }, palette: amber, props: ['Folding desk', 'Case inbox', 'Coat rack', 'Mentor station'], cast: ['YOU', 'MENTOR'], actions: [{ label: 'Return to your desk', detail: 'Open the living headquarters.', to: route.office }, { label: 'Choose a case', detail: 'Open the docket.', to: route.cases }, { label: 'Walk the city', detail: 'Open the City Directory.', to: route.map }] },
  { id: 'S02', slug: 'reception-docket', title: 'Reception and Docket Board', shortTitle: 'Docket', kicker: 'CASE INTAKE', purpose: 'Turn recommendations into a small, legible set of useful matters.', category: 'casework', layout: 'reception', minTier: 0, district: 'Founders Row', position: { x: 21, y: 70 }, palette: navy, props: ['Reception desk', 'Docket board', 'Mail cubbies', 'Waiting bench'], cast: ['MAYA', 'CLIENT', 'YOU'], actions: [{ label: 'Choose the next matter', detail: 'Enter the canonical case flow.', to: route.cases }, { label: 'Meet the client', detail: 'Preview the intake room.', to: '/world/client-intake' }, { label: 'Return to the office', detail: 'Go back to headquarters.', to: route.office }] },
  { id: 'S03', slug: 'client-intake', title: 'Client Intake Room', shortTitle: 'Client Intake', kicker: 'MATTER BRIEF', purpose: 'Preview the case contract, learning objective, and client context.', category: 'casework', layout: 'conference', minTier: 0, district: 'Founders Row', position: { x: 28, y: 78 }, palette: teal, props: ['Round table', 'Client folder', 'Privacy glass', 'Water carafe'], cast: ['CLIENT', 'YOU', 'MAYA'], actions: [{ label: 'Accept the brief', detail: 'Start or resume a case.', to: route.cases }, { label: 'Review client contracts', detail: 'Manage the client book.', to: route.clients }, { label: 'Back to reception', detail: 'Return to the docket.', to: '/world/reception-docket' }] },
  { id: 'S04', slug: 'case-workspace', title: 'Universal Case Workspace', shortTitle: 'Case Workspace', kicker: 'ACTIVE MATTER', purpose: 'Keep canonical questions, written reasoning, and correction central.', category: 'casework', layout: 'workspace', minTier: 0, district: 'Founders Row', position: { x: 37, y: 69 }, palette: navy, props: ['Argument board', 'Reading lamp', 'Evidence thread', 'Case timer'], cast: ['YOU', 'MENTOR'], actions: [{ label: 'Work the active matter', detail: 'Open the question interface.', to: route.cases }, { label: 'Conference with counsel', detail: 'Visit the mentor room.', to: '/world/mentor-conference' }, { label: 'Investigate the argument', detail: 'Open the Investigation Lab.', to: '/world/investigation-lab' }] },
  { id: 'S05', slug: 'mentor-conference', title: 'Mentor Conference', shortTitle: 'Mentor', kicker: 'FIRST-ERROR REVIEW', purpose: 'Repair the earliest unsupported reasoning step with focused tutoring.', category: 'learning', layout: 'conference', minTier: 0, district: 'Founders Row', position: { x: 43, y: 58 }, palette: plum, props: ['Redline sheet', 'Logic cards', 'Quiet lamp', 'Appeal clock'], cast: ['MENTOR', 'YOU'], actions: [{ label: 'Continue the review', detail: 'Return to current casework.', to: route.cases }, { label: 'Schedule an appeal', detail: 'Visit delayed review.', to: '/world/appeals-chamber' }, { label: 'Research a method', detail: 'Open the library.', to: '/world/research-library' }] },
  { id: 'S06', slug: 'case-resolution', title: 'Case Resolution Table', shortTitle: 'Resolution', kicker: 'VERDICT & SETTLEMENT', purpose: 'Show learning evidence before economic rewards and make recovery visible.', category: 'casework', layout: 'resolution', minTier: 0, district: 'Founders Row', position: { x: 49, y: 73 }, palette: teal, props: ['Verdict seal', 'Settlement ledger', 'Client letter', 'Redline stack'], cast: ['YOU', 'MENTOR', 'CLIENT'], actions: [{ label: 'Open the next case', detail: 'Return to useful practice.', to: route.cases }, { label: 'File the result', detail: 'Visit the Portfolio Gallery.', to: '/world/portfolio-gallery' }, { label: 'Invest the fee', detail: 'Open the design studio.', to: '/world/firm-shop' }] },
  { id: 'S07', slug: 'firm-shop', title: 'Firm Shop / Design Studio', shortTitle: 'Design Studio', kicker: 'VISIBLE PROGRESS', purpose: 'Convert earned cash into honest workflow improvements and environmental change.', category: 'firm', layout: 'shop', minTier: 0, district: 'Founders Row', position: { x: 58, y: 79 }, palette: amber, props: ['Material swatches', 'Furniture plans', 'Upgrade plinths', 'Tailor mirror'], cast: ['NINA', 'YOU'], actions: [{ label: 'Open the catalog', detail: 'Purchase compatible upgrades.', to: route.firm }, { label: 'Plan staff stations', detail: 'Review staff investments.', to: route.staff }, { label: 'Preview headquarters', detail: 'Return to the office.', to: route.office }] },
  { id: 'S08', slug: 'research-library', title: 'Research Library', shortTitle: 'Library', kicker: 'DOCTRINE & METHODS', purpose: 'Support deep review, validated explanations, and concept retrieval.', category: 'learning', layout: 'library', minTier: 1, district: 'Learning Quarter', position: { x: 18, y: 37 }, palette: amber, props: ['Book walls', 'Rolling ladder', 'Reading table', 'Reference terminal'], cast: ['AVERY', 'YOU'], actions: [{ label: 'Apply a method', detail: 'Return to a live case.', to: route.cases }, { label: 'Visit Skills Academy', detail: 'Review transfer and mastery.', to: '/world/skills-academy' }, { label: 'Trace prior reasoning', detail: 'Open the Records Room.', to: '/world/records-room' }] },
  { id: 'S09', slug: 'investigation-lab', title: 'Investigation Lab', shortTitle: 'Investigation Lab', kicker: 'ARGUMENT FORENSICS', purpose: 'Frame Logical Reasoning as evidence, conclusion, gap, and trap analysis.', category: 'learning', layout: 'lab', minTier: 1, district: 'Learning Quarter', position: { x: 28, y: 48 }, palette: navy, props: ['Evidence wall', 'Argument thread', 'Magnifier', 'Trap drawers'], cast: ['THEO', 'YOU'], actions: [{ label: 'Investigate an argument', detail: 'Work a Logical Reasoning case.', to: route.cases }, { label: 'Move to the War Room', detail: 'Open the universal workspace.', to: '/world/case-workspace' }, { label: 'Reopen a theory', detail: 'Visit Appeals.', to: '/world/appeals-chamber' }] },
  { id: 'S10', slug: 'due-diligence', title: 'Due Diligence Deal Room', shortTitle: 'Due Diligence', kicker: 'PASSAGE ANALYSIS', purpose: 'Frame Reading Comprehension as viewpoint, structure, role, and inference diligence.', category: 'learning', layout: 'deal', minTier: 1, district: 'Learning Quarter', position: { x: 39, y: 38 }, palette: blue, props: ['Passage wall', 'Viewpoint cards', 'Risk matrix', 'Deal table'], cast: ['AVERY', 'PARTNER', 'YOU'], actions: [{ label: 'Run the diligence', detail: 'Work a Reading Comprehension case.', to: route.cases }, { label: 'Review capital', detail: 'Visit the boardroom.', to: '/world/capital-boardroom' }, { label: 'Check the passage map', detail: 'Visit the library.', to: '/world/research-library' }] },
  { id: 'S11', slug: 'appeals-chamber', title: 'Appeals Chamber', shortTitle: 'Appeals', kicker: 'DELAYED RECOVERY', purpose: 'Turn misses and uncertain answers into spaced, evidence-based recovery.', category: 'learning', layout: 'court', minTier: 1, district: 'Civic Center', position: { x: 50, y: 29 }, palette: plum, props: ['Appeals bench', 'Redline docket', 'Review clock', 'Precedent shelf'], cast: ['REVIEWER', 'MENTOR', 'YOU'], actions: [{ label: 'Hear the next appeal', detail: 'Retrieve a corrected method.', to: route.cases }, { label: 'Inspect the redline', detail: 'Return to Mentor Conference.', to: '/world/mentor-conference' }, { label: 'File recovered work', detail: 'Open the portfolio.', to: '/world/portfolio-gallery' }] },
  { id: 'S12', slug: 'skills-academy', title: 'Skills Academy', shortTitle: 'Skills Academy', kicker: 'GUIDED → INDEPENDENT', purpose: 'Show skill coverage and transfer from supported reasoning to independent performance.', category: 'learning', layout: 'academy', minTier: 1, district: 'Learning Quarter', position: { x: 59, y: 38 }, palette: teal, props: ['Skill map', 'Training dais', 'Practice stations', 'Mastery banners'], cast: ['MENTOR', 'AVERY', 'YOU'], actions: [{ label: 'Begin an independent file', detail: 'Apply the next method.', to: route.cases }, { label: 'Enter Mock Court', detail: 'Preview transfer under constraint.', to: '/world/mock-courtroom' }, { label: 'Review the method', detail: 'Return to the library.', to: '/world/research-library' }] },
  { id: 'S13', slug: 'staff-bullpen', title: 'Staff Bullpen', shortTitle: 'Staff Bullpen', kicker: 'YOUR TEAM', purpose: 'Make staff functions, capacity, and visible office activity understandable.', category: 'firm', layout: 'bullpen', minTier: 2, district: 'Firm Campus', position: { x: 65, y: 70 }, palette: navy, props: ['Shared desks', 'Assignment board', 'Printer bank', 'Team lockers'], cast: ['MAYA', 'ASSOCIATE', 'NINA', 'YOU'], actions: [{ label: 'Manage the team', detail: 'Hire compatible staff.', to: route.staff }, { label: 'Open interviews', detail: 'Visit the Hiring Room.', to: '/world/hiring-room' }, { label: 'Review assignments', detail: 'Visit Operations.', to: '/world/operations-office' }] },
  { id: 'S14', slug: 'hiring-room', title: 'Hiring and Interview Room', shortTitle: 'Hiring Room', kicker: 'BUILD THE BENCH', purpose: 'Present staff purchases as clear workflow choices rather than randomized characters.', category: 'firm', layout: 'interview', minTier: 2, district: 'Firm Campus', position: { x: 73, y: 77 }, palette: amber, props: ['Interview table', 'Candidate files', 'Role board', 'Glass door'], cast: ['NINA', 'CANDIDATE', 'YOU'], actions: [{ label: 'Review candidates', detail: 'Open the staff catalog.', to: route.staff }, { label: 'Tour the bullpen', detail: 'See the current team.', to: '/world/staff-bullpen' }, { label: 'Check the budget', detail: 'Open firm management.', to: route.firm }] },
  { id: 'S15', slug: 'operations-office', title: 'Operations Office', shortTitle: 'Operations', kicker: 'WEEKLY CAPACITY', purpose: 'Show active workload, review obligations, and sustainable targets.', category: 'firm', layout: 'operations', minTier: 2, district: 'Firm Campus', position: { x: 80, y: 63 }, palette: blue, props: ['Capacity board', 'Calendar wall', 'Case trays', 'Workflow screen'], cast: ['NINA', 'MAYA', 'YOU'], actions: [{ label: 'Work today’s docket', detail: 'Return to headquarters.', to: route.office }, { label: 'Review due matters', detail: 'Visit Appeals.', to: '/world/appeals-chamber' }, { label: 'Manage the firm', detail: 'Adjust workflow investments.', to: route.firm }] },
  { id: 'S16', slug: 'practice-group-hall', title: 'Practice Group Hall', shortTitle: 'Practice Groups', kicker: 'SPECIALIZATION', purpose: 'Organize balanced skill development across visible practice groups.', category: 'firm', layout: 'hall', minTier: 2, district: 'Firm Campus', position: { x: 61, y: 57 }, palette: teal, props: ['Group doors', 'Progress map', 'Weekly brief', 'Team banners'], cast: ['PARTNER', 'ASSOCIATE', 'YOU'], actions: [{ label: 'Train a weak group', detail: 'Visit Skills Academy.', to: '/world/skills-academy' }, { label: 'Manage assignments', detail: 'Open Operations.', to: '/world/operations-office' }, { label: 'Enter Mock Court', detail: 'Test independent transfer.', to: '/world/mock-courtroom' }] },
  { id: 'S17', slug: 'mock-courtroom', title: 'Mock Courtroom', shortTitle: 'Mock Court', kicker: 'TRANSFER HEARING', purpose: 'Frame optional timed transfer after accuracy and demonstrated reasoning.', category: 'learning', layout: 'court', minTier: 2, district: 'Civic Center', position: { x: 69, y: 44 }, palette: navy, props: ['Judge bench', 'Counsel tables', 'Hearing clock', 'Observation rail'], cast: ['JUDGE', 'YOU', 'MENTOR'], actions: [{ label: 'Work an independent hearing', detail: 'Open a canonical case.', to: route.cases }, { label: 'Train first', detail: 'Visit Skills Academy.', to: '/world/skills-academy' }, { label: 'Return to practice groups', detail: 'Open the hall.', to: '/world/practice-group-hall' }] },
  { id: 'S18', slug: 'portfolio-gallery', title: 'Portfolio Gallery', shortTitle: 'Portfolio', kicker: 'EVIDENCE OF GROWTH', purpose: 'Celebrate resolved matters, recovered errors, and durable milestones.', category: 'learning', layout: 'gallery', minTier: 2, district: 'Firm Campus', position: { x: 53, y: 58 }, palette: plum, props: ['Case frames', 'Recovery wall', 'Milestone plinths', 'Firm timeline'], cast: ['YOU', 'MENTOR', 'CLIENT'], actions: [{ label: 'Review achievements', detail: 'Open earned milestones.', to: route.achievements }, { label: 'Inspect complete files', detail: 'Visit Records.', to: '/world/records-room' }, { label: 'Reopen a matter', detail: 'Visit Appeals.', to: '/world/appeals-chamber' }] },
  { id: 'S19', slug: 'records-room', title: 'Records Room', shortTitle: 'Records', kicker: 'CASE HISTORY', purpose: 'Investigate prior attempts, briefs, tutor turns, and case-state evidence.', category: 'learning', layout: 'records', minTier: 1, district: 'Learning Quarter', position: { x: 34, y: 56 }, palette: amber, props: ['Archive aisles', 'Rolling carts', 'Search terminal', 'Sealed boxes'], cast: ['MAYA', 'REVIEWER', 'YOU'], actions: [{ label: 'Return to current work', detail: 'Open active casework.', to: route.cases }, { label: 'View curated matters', detail: 'Visit the Portfolio.', to: '/world/portfolio-gallery' }, { label: 'Inspect content review', detail: 'Preview internal operations.', to: '/world/content-review-office' }] },
  { id: 'S20', slug: 'capital-boardroom', title: 'Capital Allocation Boardroom', shortTitle: 'Capital Boardroom', kicker: 'INVESTMENT COMMITTEE', purpose: 'Allocate earned firm resources without allowing money to buy mastery.', category: 'firm', layout: 'boardroom', minTier: 3, district: 'Executive District', position: { x: 82, y: 42 }, palette: navy, props: ['Long table', 'Investment screen', 'Allocation ledger', 'City model'], cast: ['PARTNER', 'NINA', 'YOU'], actions: [{ label: 'Allocate capital', detail: 'Open firm purchases.', to: route.firm }, { label: 'Review geography', detail: 'Open the City Directory.', to: route.map }, { label: 'Check diligence', detail: 'Visit the Deal Room.', to: '/world/due-diligence' }] },
  { id: 'S21', slug: 'partner-office', title: 'Partner Office', shortTitle: 'Partner Office', kicker: 'LONG-RANGE COUNSEL', purpose: 'Connect rank, firm milestones, analytics, and the next honest objective.', category: 'firm', layout: 'partner', minTier: 3, district: 'Executive District', position: { x: 76, y: 28 }, palette: navy, props: ['Partner desk', 'City window', 'Rank wall', 'Strategy table'], cast: ['PARTNER', 'YOU'], actions: [{ label: 'Review the empire plan', detail: 'Open the city map.', to: route.map }, { label: 'Authorize investment', detail: 'Open firm management.', to: route.firm }, { label: 'Review the week', detail: 'Visit the Rooftop.', to: '/world/rooftop-skyline' }] },
  { id: 'S22', slug: 'client-site', title: 'Client Site / Field Office', shortTitle: 'Client Site', kicker: 'FIELD MATTER', purpose: 'Add procedural visual variety without changing canonical question content.', category: 'casework', layout: 'field', minTier: 2, district: 'Client Corridor', position: { x: 88, y: 56 }, palette: blue, props: ['Portable table', 'Client brand wall', 'Travel cases', 'City view'], cast: ['CLIENT', 'THEO', 'YOU'], actions: [{ label: 'Open the field matter', detail: 'Enter the canonical case interface.', to: route.cases }, { label: 'Review the client', detail: 'Open contracts.', to: route.clients }, { label: 'Travel to court', detail: 'Visit Courthouse Steps.', to: '/world/courthouse-steps' }] },
  { id: 'S23', slug: 'courthouse-steps', title: 'Courthouse Steps', shortTitle: 'Courthouse', kicker: 'MILESTONE MATTER', purpose: 'Frame major matters and results while preserving independent reasoning.', category: 'world', layout: 'courthouse', minTier: 2, district: 'Civic Center', position: { x: 72, y: 17 }, palette: stone, props: ['Stone steps', 'Columns', 'Press rail', 'Case banner'], cast: ['CLIENT', 'MENTOR', 'YOU'], actions: [{ label: 'Enter the courthouse', detail: 'Open an independent case.', to: route.cases }, { label: 'Visit Mock Court', detail: 'Enter the training courtroom.', to: '/world/mock-courtroom' }, { label: 'Return to the city', detail: 'Open the map.', to: route.map }] },
  { id: 'S24', slug: 'break-room', title: 'Break Room / Café', shortTitle: 'Counsel Café', kicker: 'QUIET MINUTE', purpose: 'Offer optional decompression and character flavor with no relationship grind.', category: 'social', layout: 'cafe', minTier: 2, district: 'Firm Campus', position: { x: 61, y: 84 }, palette: teal, props: ['Coffee counter', 'Small tables', 'Notice board', 'Plants'], cast: ['MAYA', 'ASSOCIATE', 'NINA', 'YOU'], actions: [{ label: 'Return refreshed', detail: 'Go back to headquarters.', to: route.office }, { label: 'Return to the team floor', detail: 'Visit the Bullpen.', to: '/world/staff-bullpen' }, { label: 'Open the docket', detail: 'Do useful casework.', to: route.cases }] },
  { id: 'S25', slug: 'city-directory', title: 'City Directory', shortTitle: 'City Directory', kicker: 'FAST TRAVEL', purpose: 'Make the firm’s expanding footprint and every scene destination visible.', category: 'world', layout: 'directory', minTier: 0, district: 'Citywide', position: { x: 46, y: 48 }, palette: blue, props: ['District map', 'Transit routes', 'Firm markers', 'Future lots'], cast: ['YOU', 'NINA'], actions: [{ label: 'Explore the complete city', detail: 'Open the interactive Empire map.', to: route.map }, { label: 'Return to headquarters', detail: 'Go back to the office.', to: route.office }, { label: 'Open the next case', detail: 'Return to the learning engine.', to: route.cases }] },
  { id: 'S26', slug: 'rooftop-skyline', title: 'Rooftop / Skyline', shortTitle: 'Rooftop', kicker: 'WEEKLY REFLECTION', purpose: 'Show firm scale, learning volume, and progress in a quiet milestone scene.', category: 'social', layout: 'rooftop', minTier: 3, district: 'Executive District', position: { x: 59, y: 17 }, palette: navy, props: ['Skyline', 'Firm sign', 'Terrace', 'Weekly ledger'], cast: ['MENTOR', 'ASSOCIATE', 'YOU'], actions: [{ label: 'Review personal evidence', detail: 'Visit the Portfolio.', to: '/world/portfolio-gallery' }, { label: 'Set the next milestone', detail: 'Visit the Partner Office.', to: '/world/partner-office' }, { label: 'Return to work', detail: 'Open the case docket.', to: route.cases }] },
  { id: 'S27', slug: 'managing-partner-floor', title: 'Managing Partner Floor', shortTitle: 'Managing Partner', kicker: 'ENDGAME HEADQUARTERS', purpose: 'Unify firm-wide portfolio, expansion, mentorship, and the full legal empire.', category: 'firm', layout: 'executive', minTier: 5, district: 'Executive District', position: { x: 88, y: 16 }, palette: navy, props: ['Executive lobby', 'Global map', 'Portfolio wall', 'Mentorship table'], cast: ['PARTNER', 'ASSOCIATE', 'NINA', 'YOU'], actions: [{ label: 'Direct the empire', detail: 'Open the complete map.', to: route.map }, { label: 'Chair capital allocation', detail: 'Visit the Boardroom.', to: '/world/capital-boardroom' }, { label: 'Take a case yourself', detail: 'Return to the learning engine.', to: route.cases }] },
  { id: 'S28', slug: 'content-review-office', title: 'Content Review Office', shortTitle: 'Content Review', kicker: 'INTERNAL OPERATIONS', purpose: 'Scaffold auditable validation, duplicate review, licensing, and publication workflows.', category: 'internal', layout: 'review', minTier: 0, internal: true, district: 'Operations Annex', position: { x: 8, y: 55 }, palette: plum, props: ['Review queues', 'Quarantine shelf', 'Audit terminal', 'Publication board'], cast: ['REVIEWER', 'AVERY', 'NINA'], actions: [{ label: 'Return to learner records', detail: 'Visit the Records Room.', to: '/world/records-room' }, { label: 'Return to the city', detail: 'Open the map.', to: route.map }] },
]

export const sceneBySlug = new Map(scenes.map((scene) => [scene.slug, scene]))
export const learnerScenes = scenes.filter((scene) => !scene.internal)
